import { PageData } from './types';

export const INITIAL_DATA: PageData = {
  hero: {
    title: '',
    subtitle: '',
    date: '2027-01-01T00:00:00',
    ctaText: 'COMPRAR ENTRADAS',
    ctaUrl: '#buy',
    bgImage: '',
    videoUrl: '',
  },
  welcome: {
    subtitle1: '',
    title1: '',
    desc1: '',
    img1: '',
    video1: '',
    accordion: [],
    accordion2: [],
    title2: '',
    subtitle2: '',
    desc2: '',
    img2: '',
    video2: '',
    btnText2: '',
    btnUrl2: '',
  },
  lineup: {
    title: '',
    subtitle: 'LINE UP',
    artists: [],
  },
  experience: {
    title: '',
    items: [],
  },
  lodging: {
    title: '',
    subtitle: '',
    desc: '',
    suites: [],
  },
  caliPackage: {
    title: 'ITINERARIO DÍA A DÍA',
    desc: 'Descubre la programación y actividades planificadas para cada uno de los 4 días de la experiencia Taybeach.',
    icon: 'Calendar',
    items: [
      {
        title: 'Día 1 | BIENVENIDOS A TAYBEACH HOTEL',
        desc: '• Llegada a Santa Marta y traslado al hotel Taybeach.\n• Tiempo para instalarte y conectar con el entorno.\n• Noche: Cena de bienvenida (8:00 PM) + Ritual de Fuego y Conexión.',
        hidden: false,
      },
      {
        title: 'Día 2 | WELLNESS & BEACH PARTY',
        desc: '• Mañana: Desayuno + Clases Wellness (Core, Yoga, Sound Healing, Voleibol).\n• Tarde: Main Stage (Escenario principal frente al mar).',
        hidden: false,
      },
      {
        title: 'Día 3 | POOL PARTY',
        desc: '• Mañana: Desayuno.\n• Tarde: Pool Party.\n• Noche: After Party frente al mar.',
        hidden: false,
      },
      {
        title: 'Día 4 | CHECK-OUT Y REGRESO',
        desc: '• Mañana: Desayuno.\n• Traslado de regreso al Aeropuerto de Santa Marta.',
        hidden: false,
      },
    ],
    btnText: 'RESERVAR EXPERIENCIA',
    btnUrl: '#buy',
  },
  tickets: {
    title: '',
    subtitle: '',
    tiers: [],
  },
  faqs: {
    title: '',
    subtitle: 'FAQ',
    items: [],
  },
  buy: {
    title: '',
    description: '',
    widgetUrl: '',
  },
  footer: {
    description: '',
    address: '',
    phone: '',
    email: '',
    social: {
      instagram: '',
      facebook: '',
      twitter: '',
    },
  },
  settings: {
    accentColor: '#D4AF37',
    faviconUrl: '',
    headerLogoUrl: '',
    footerLogoUrl: '',
    adminLogoUrl: '',
    whatsappNumber: '',
    navBrandText: 'REAL PEOPLE',
    siteName: 'Real People',
    loadingText: 'CARGANDO...',
    loadingColor: '#FFFFFF',
    fontDisplay: 'Space Grotesk',
    fontSans: 'Inter',
    fontDisplayUrl: '',
    fontSansUrl: '',
    logoSize: 60,
    mobileLogoSize: 48,
    footerLogoSize: 80,
    footerMobileLogoSize: 60,
    globalBgType: 'blurred',
    globalBgImage: '',
    globalBgImageMobile: '',
    globalBgImageDesktop: '',
    globalBgColor: '#000000',
  },
  sectionOrder: ['welcome', 'experience', 'lineup', 'lodging', 'caliPackage', 'tickets', 'buy', 'faqs'],
  hiddenSections: [],
  sectionLabels: {
    welcome: 'BIENVENIDA',
    experience: 'EXPERIENCIA',
    lineup: 'LINE UP',
    lodging: 'HOSPEDAJE',
    caliPackage: 'ITINERARIO',
    tickets: 'BOLETERÍA',
    buy: 'COMPRAR',
    faqs: 'PREGUNTAS',
  },
  seo: {
    title: 'Real People | Eventos Exclusivos',
    description: 'Experiencias únicas de entretenimiento premium en Colombia.',
    image: '',
    keywords: 'eventos, colombia, musica electronica, real people, realpeoplecol',
  },
};
