import { PageData } from './types';

export const INITIAL_DATA: PageData = {
  hero: {
    title: '',
    subtitle: '',
    date: '2027-01-01T00:00:00',
    ctaText: 'COMPRAR ENTRADAS',
    ctaUrl: '#buy',
    bgImage: '',
    videoUrl: '',
  },
  welcome: {
    subtitle1: '',
    title1: '',
    desc1: '',
    img1: '',
    video1: '',
    accordion: [],
    accordion2: [],
    title2: '',
    subtitle2: '',
    desc2: '',
    img2: '',
    video2: '',
    btnText2: '',
    btnUrl2: '',
  },
  lineup: {
    title: '',
    subtitle: 'LINE UP',
    artists: [],
  },
  experience: {
    title: '',
    items: [],
  },
  lodging: {
    title: '',
    subtitle: '',
    desc: '',
    suites: [],
  },
  caliPackage: {
    title: '',
    desc: '',
    icon: 'Plane',
    items: [],
    btnText: '',
    btnUrl: '',
  },
  tickets: {
    title: '',
    subtitle: '',
    tiers: [],
  },
  faqs: {
    title: '',
    subtitle: 'FAQ',
    items: [],
  },
  buy: {
    title: '',
    description: '',
    widgetUrl: '',
  },
  footer: {
    description: '',
    address: '',
    phone: '',
    email: '',
    social: {
      instagram: '',
      facebook: '',
      twitter: '',
    },
  },
  settings: {
    accentColor: '#D4AF37',
    faviconUrl: '',
    headerLogoUrl: '',
    footerLogoUrl: '',
    adminLogoUrl: '',
    whatsappNumber: '',
    navBrandText: 'REAL PEOPLE',
    siteName: 'Real People',
    loadingText: 'CARGANDO...',
    loadingColor: '#FFFFFF',
    fontDisplay: 'Space Grotesk',
    fontSans: 'Inter',
    fontDisplayUrl: '',
    fontSansUrl: '',
    logoSize: 60,
    mobileLogoSize: 48,
    footerLogoSize: 80,
    footerMobileLogoSize: 60,
    globalBgType: 'blurred',
    globalBgImage: '',
    globalBgImageMobile: '',
    globalBgImageDesktop: '',
    globalBgColor: '#000000',
  },
  sectionOrder: ['welcome', 'experience', 'lineup', 'lodging', 'caliPackage', 'tickets', 'buy', 'faqs'],
  hiddenSections: [],
  sectionLabels: {
    welcome: 'BIENVENIDA',
    experience: 'EXPERIENCIA',
    lineup: 'LINE UP',
    lodging: 'HOSPEDAJE',
    caliPackage: 'PAQUETE CALI',
    tickets: 'BOLETERÍA',
    buy: 'COMPRAR',
    faqs: 'PREGUNTAS',
  },
  seo: {
    title: 'Real People | Eventos Exclusivos',
    description: 'Experiencias únicas de entretenimiento premium en Colombia.',
    image: '',
    keywords: 'eventos, colombia, musica electronica, real people, realpeoplecol',
  },
};
